# Backend deployment workflow
name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'server/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and test backend
        run: |
          cd server
          npm install
          npm run test --if-present

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build backend
        run: |
          cd server
          npm install
          npm run build

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./server

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./backend-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B148E23A8C8453CB552EDDC7B52A414 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D11190169A7F44A4A996E138EB3C6EA8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4E6BE3F7C314607BBC4FAA52AF2E513 }}

      - name: 'Deploy Backend to Azure Web App'
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: '2227609'
          slot-name: 'Production'
          package: ./backend-app
          resource-group-name: 'atix-fullstack-2.1'