# Frontend deployment workflow
name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'client/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and test frontend
        run: |
          cd client
          npm install
          npm run test -- --watch=false --browsers=ChromeHeadless

  build-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Build frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: ./client/dist

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./frontend-dist
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B148E23A8C8453CB552EDDC7B52A414 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D11190169A7F44A4A996E138EB3C6EA8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4E6BE3F7C314607BBC4FAA52AF2E513 }}

      - name: 'Deploy Frontend to Azure Web App'
        id: deploy-frontend
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Client-2227609'
          slot-name: 'Production'
          package: ./frontend-dist
          resource-group-name: 'atix-fullstack-2.1'