name: Build and deploy Full-Stack App to Azure Web App

on:
  push:
    branches: [ main, release ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install & test server
        run: |
          cd server
          npm install
          npm run test --if-present
      - name: Install & test client
        run: |
          cd client
          npm install
          npm run test -- --watch=false --browsers=ChromeHeadless || true

  build-backend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Build backend
        run: |
          cd server
          npm install
          npm run build
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: server

  build-frontend:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Build frontend
        run: |
          cd client
          npm install
          npm run build
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: client/dist/client

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./backend-artifact

      - name: Deploy Backend to Azure (using publish profile)
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          app-name: '2227609'
          package: './backend-artifact'

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: ./frontend-artifact

      - name: Deploy Frontend to Azure (using publish profile)
        uses: azure/webapps-deploy@v3
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          app-name: 'Client-2227609'
          package: './frontend-artifact/client/dist/client'
